"""
训练配置优化模块
包含优化的训练超参数、学习率策略、数据增强配置
用于YOLOv8/11骨折检测优化
"""

from typing import Dict, Any, Optional
import torch


class OptimizedTrainingConfig:
    """
    优化的训练配置类
    针对医学影像骨折检测场景优化
    """
    
    # 默认优化配置
    DEFAULT_CONFIG = {
        # 基础训练参数
        'epochs': 200,
        'batch': 16,
        'imgsz': 640,
        'patience': 50,
        
        # 优化器设置
        'optimizer': 'AdamW',  # AdamW比SGD更适合医学图像
        'lr0': 0.001,          # 降低初始学习率，更稳定
        'lrf': 0.01,           # 最终学习率比例
        'momentum': 0.937,
        'weight_decay': 0.0005,
        
        # 学习率调度
        'lr_scheduler': 'cosine',  # 余弦退火
        'warmup_epochs': 5,        # 增加预热轮数
        'warmup_momentum': 0.8,
        'warmup_bias_lr': 0.1,
        
        # 数据增强
        'hsv_h': 0.015,        # HSV色调（医学图像慎用）
        'hsv_s': 0.7,
        'hsv_v': 0.4,
        'degrees': 5.0,        # 小角度旋转，保持解剖结构
        'translate': 0.1,
        'scale': 0.2,
        'shear': 2.0,
        'flipud': 0.0,         # 禁用上下翻转
        'fliplr': 0.5,
        'mosaic': 1.0,
        'mixup': 0.1,
        'copy_paste': 0.1,
        'auto_augment': 'randaugment',
        'erasing': 0.4,
        
        # 损失函数权重
        'box': 7.5,            # 增加边界框损失权重
        'cls': 0.5,
        'dfl': 1.5,
        
        # 多尺度训练
        'multi_scale': True,
        'scale_range': [0.5, 1.5],  # 320-960
        
        # 标签分配
        'label_assignment': 'dynamic',  # dynamic, simota, task_aligned
        'switch_epoch': 100,            # 动态分配切换轮数
        
        # 损失函数类型
        'box_loss_type': 'siou',   # siou, eiou, ciou
        'cls_loss_type': 'focal',  # focal, bce, qfl
        
        # 早停和保存
        'save_period': 10,
        'val_period': 1,
        
        # 其他
        'dropout': 0.0,
        'workers': 8,
        'rect': False,
        'resume': False,
        'amp': True,           # 混合精度训练
        'cache': True,         # 缓存数据到内存
    }
    
    # 医学影像专用配置
    MEDICAL_CONFIG = {
        # 更保守的增强策略
        'degrees': 3.0,        # 更小的旋转角度
        'translate': 0.05,     # 更小的平移
        'scale': 0.1,          # 更小的缩放
        'shear': 1.0,
        'hsv_h': 0.01,         # 更保守的颜色增强
        'hsv_s': 0.5,
        'hsv_v': 0.3,
        
        # 更长的训练
        'epochs': 300,
        'patience': 100,
        'warmup_epochs': 10,
        
        # 更小的学习率
        'lr0': 0.0005,
        'lrf': 0.01,
        
        # 更大的批次
        'batch': 32,
        
        # 医学影像专用损失权重
        'box': 10.0,           # 更重视定位精度
        'cls': 0.3,
        'dfl': 2.0,
    }
    
    # 快速训练配置（用于实验）
    FAST_CONFIG = {
        'epochs': 50,
        'batch': 64,
        'patience': 20,
        'warmup_epochs': 3,
        'imgsz': 416,
        'multi_scale': False,
    }
    
    def __init__(self, config_type: str = 'default', **kwargs):
        """
        初始化训练配置
        
        Args:
            config_type: 配置类型 ('default', 'medical', 'fast')
            **kwargs: 自定义配置参数
        """
        if config_type == 'medical':
            self.config = {**self.DEFAULT_CONFIG, **self.MEDICAL_CONFIG}
        elif config_type == 'fast':
            self.config = {**self.DEFAULT_CONFIG, **self.FAST_CONFIG}
        else:
            self.config = self.DEFAULT_CONFIG.copy()
        
        # 更新自定义参数
        self.config.update(kwargs)
    
    def get(self, key: str, default: Any = None) -> Any:
        """获取配置参数"""
        return self.config.get(key, default)
    
    def set(self, key: str, value: Any) -> None:
        """设置配置参数"""
        self.config[key] = value
    
    def to_dict(self) -> Dict[str, Any]:
        """转换为字典"""
        return self.config.copy()
    
    def get_hyp_yaml_content(self) -> str:
        """
        生成YOLO的hyp.yaml配置文件内容
        """
        content = f"""# Optimized Hyperparameters for Bone Fracture Detection
# Generated by OptimizedTrainingConfig

# Optimizer
optimizer: {self.config['optimizer']}
lr0: {self.config['lr0']}
lrf: {self.config['lrf']}
momentum: {self.config['momentum']}
weight_decay: {self.config['weight_decay']}

# Learning rate schedule
lr_scheduler: {self.config['lr_scheduler']}
warmup_epochs: {self.config['warmup_epochs']}
warmup_momentum: {self.config['warmup_momentum']}
warmup_bias_lr: {self.config['warmup_bias_lr']}

# Augmentation
hsv_h: {self.config['hsv_h']}
hsv_s: {self.config['hsv_s']}
hsv_v: {self.config['hsv_v']}
degrees: {self.config['degrees']}
translate: {self.config['translate']}
scale: {self.config['scale']}
shear: {self.config['shear']}
flipud: {self.config['flipud']}
fliplr: {self.config['fliplr']}
mosaic: {self.config['mosaic']}
mixup: {self.config['mixup']}
copy_paste: {self.config['copy_paste']}

# Loss weights
box: {self.config['box']}
cls: {self.config['cls']}
dfl: {self.config['dfl']}

# Other
epochs: {self.config['epochs']}
patience: {self.config['patience']}
dropout: {self.config['dropout']}
"""
        return content
    
    def save_hyp_yaml(self, path: str) -> None:
        """保存hyp.yaml文件"""
        with open(path, 'w') as f:
            f.write(self.get_hyp_yaml_content())


def get_medical_augmentation_pipeline():
    """
    获取医学影像专用的数据增强管道
    使用albumentations库
    
    Returns:
        增强管道
    """
    try:
        import albumentations as A
        from albumentations.pytorch import ToTensorV2
        
        transform = A.Compose([
            # 几何变换（保守）
            A.ShiftScaleRotate(
                shift_limit=0.05,
                scale_limit=0.1,
                rotate_limit=5,
                border_mode=0,
                p=0.5
            ),
            
            # 对比度增强
            A.CLAHE(
                clip_limit=2.0,
                tile_grid_size=(8, 8),
                p=0.3
            ),
            
            # 锐化
            A.Sharpen(
                alpha=(0.2, 0.5),
                lightness=(0.5, 1.0),
                p=0.3
            ),
            
            # 噪声（模拟设备噪声）
            A.GaussNoise(
                var_limit=(10.0, 50.0),
                p=0.2
            ),
            
            # 模糊（模拟运动伪影）
            A.GaussianBlur(
                blur_limit=(3, 7),
                p=0.2
            ),
            
            # 亮度对比度
            A.RandomBrightnessContrast(
                brightness_limit=0.2,
                contrast_limit=0.2,
                p=0.3
            ),
            
            # 归一化
            A.Normalize(
                mean=[0.485, 0.456, 0.406],
                std=[0.229, 0.224, 0.225]
            ),
            
            ToTensorV2()
        ], bbox_params=A.BboxParams(
            format='yolo',
            label_fields=['class_labels'],
            min_visibility=0.3
        ))
        
        return transform
    
    except ImportError:
        print("Warning: albumentations not installed. Using default augmentation.")
        return None


def get_optimizer(model, config: Dict[str, Any]):
    """
    获取优化器
    
    Args:
        model: 模型
        config: 配置字典
    
    Returns:
        优化器
    """
    optimizer_type = config.get('optimizer', 'AdamW')
    lr0 = config.get('lr0', 0.001)
    momentum = config.get('momentum', 0.937)
    weight_decay = config.get('weight_decay', 0.0005)
    
    # 分组参数（对偏置和BN层使用不同学习率）
    g = [], [], []  # optimizer parameter groups
    bn = tuple(v for k, v in nn.__dict__.items() if 'Norm' in k)  # normalization layers
    
    for v in model.modules():
        if hasattr(v, 'bias') and isinstance(v.bias, nn.Parameter):
            g[2].append(v.bias)  # biases
        if isinstance(v, bn):
            g[1].append(v.weight)  # no decay
        elif hasattr(v, 'weight') and isinstance(v.weight, nn.Parameter):
            g[0].append(v.weight)  # weights with decay
    
    if optimizer_type == 'Adam':
        optimizer = torch.optim.Adam(g[2], lr=lr0, betas=(momentum, 0.999))
    elif optimizer_type == 'AdamW':
        optimizer = torch.optim.AdamW(g[2], lr=lr0, betas=(momentum, 0.999), weight_decay=0.0)
    elif optimizer_type == 'SGD':
        optimizer = torch.optim.SGD(g[2], lr=lr0, momentum=momentum, nesterov=True)
    else:
        raise ValueError(f"Unsupported optimizer: {optimizer_type}")
    
    # 添加其他参数组
    optimizer.add_param_group({'params': g[0], 'weight_decay': weight_decay})  # weights with decay
    optimizer.add_param_group({'params': g[1], 'weight_decay': 0.0})  # no decay (biases)
    
    return optimizer


def get_lr_scheduler(optimizer, config: Dict[str, Any], epochs: int):
    """
    获取学习率调度器
    
    Args:
        optimizer: 优化器
        config: 配置字典
        epochs: 总训练轮数
    
    Returns:
        学习率调度器
    """
    scheduler_type = config.get('lr_scheduler', 'cosine')
    lrf = config.get('lrf', 0.01)
    
    if scheduler_type == 'cosine':
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            optimizer,
            T_max=epochs,
            eta_min=optimizer.param_groups[0]['lr'] * lrf
        )
    elif scheduler_type == 'step':
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer,
            step_size=epochs // 3,
            gamma=0.1
        )
    elif scheduler_type == 'exponential':
        scheduler = torch.optim.lr_scheduler.ExponentialLR(
            optimizer,
            gamma=0.95
        )
    elif scheduler_type == 'warmup_cosine':
        # 预热 + 余弦退火
        warmup_epochs = config.get('warmup_epochs', 5)
        
        def lr_lambda(epoch):
            if epoch < warmup_epochs:
                return epoch / warmup_epochs
            else:
                progress = (epoch - warmup_epochs) / (epochs - warmup_epochs)
                return 0.5 * (1 + torch.cos(torch.tensor(progress * 3.14159)))
        
        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
    else:
        scheduler = None
    
    return scheduler


def get_training_args(config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """
    获取YOLO训练参数字典
    
    Args:
        config: 配置字典，如果为None则使用默认配置
    
    Returns:
        训练参数字典
    """
    if config is None:
        config = OptimizedTrainingConfig().to_dict()
    
    args = {
        'epochs': config.get('epochs', 200),
        'batch': config.get('batch', 16),
        'imgsz': config.get('imgsz', 640),
        'patience': config.get('patience', 50),
        'optimizer': config.get('optimizer', 'AdamW'),
        'lr0': config.get('lr0', 0.001),
        'lrf': config.get('lrf', 0.01),
        'momentum': config.get('momentum', 0.937),
        'weight_decay': config.get('weight_decay', 0.0005),
        'warmup_epochs': config.get('warmup_epochs', 5),
        'box': config.get('box', 7.5),
        'cls': config.get('cls', 0.5),
        'dfl': config.get('dfl', 1.5),
        'hsv_h': config.get('hsv_h', 0.015),
        'hsv_s': config.get('hsv_s', 0.7),
        'hsv_v': config.get('hsv_v', 0.4),
        'degrees': config.get('degrees', 5.0),
        'translate': config.get('translate', 0.1),
        'scale': config.get('scale', 0.2),
        'shear': config.get('shear', 2.0),
        'flipud': config.get('flipud', 0.0),
        'fliplr': config.get('fliplr', 0.5),
        'mosaic': config.get('mosaic', 1.0),
        'mixup': config.get('mixup', 0.1),
        'copy_paste': config.get('copy_paste', 0.1),
        'erasing': config.get('erasing', 0.4),
        'dropout': config.get('dropout', 0.0),
        'workers': config.get('workers', 8),
        'rect': config.get('rect', False),
        'resume': config.get('resume', False),
        'amp': config.get('amp', True),
        'cache': config.get('cache', True),
        'save_period': config.get('save_period', 10),
    }
    
    return args


# ============ 预设配置 ============

# 高分辨率训练配置（适合细节检测）
HIGH_RES_CONFIG = {
    'imgsz': 1280,
    'batch': 8,  # 减小批次以适应大图像
    'multi_scale': True,
    'scale_range': [0.25, 1.0],  # 320-1280
}

# 小目标检测优化配置
SMALL_OBJECT_CONFIG = {
    'imgsz': 640,
    'box': 10.0,  # 增加定位损失权重
    'dfl': 2.0,
    'mosaic': 1.0,
    'copy_paste': 0.3,  # 增加copy-paste增强
    'degrees': 10.0,    # 更大的旋转范围
}

# 快速推理优化配置
FAST_INFERENCE_CONFIG = {
    'imgsz': 416,
    'batch': 64,
    'multi_scale': False,
    'mosaic': 0.0,  # 禁用mosaic
    'mixup': 0.0,
}


def get_preset_config(preset_name: str) -> Dict[str, Any]:
    """
    获取预设配置
    
    Args:
        preset_name: 预设名称 ('high_res', 'small_object', 'fast_inference')
    
    Returns:
        配置字典
    """
    presets = {
        'high_res': HIGH_RES_CONFIG,
        'small_object': SMALL_OBJECT_CONFIG,
        'fast_inference': FAST_INFERENCE_CONFIG,
    }
    
    return presets.get(preset_name, {})


# ============ 测试代码 ============
if __name__ == "__main__":
    print("Testing Training Configuration...")
    
    # 测试默认配置
    print("\n1. Testing Default Config:")
    default_config = OptimizedTrainingConfig('default')
    print(f"   Epochs: {default_config.get('epochs')}")
    print(f"   Batch: {default_config.get('batch')}")
    print(f"   Optimizer: {default_config.get('optimizer')}")
    print(f"   Box loss weight: {default_config.get('box')}")
    
    # 测试医学配置
    print("\n2. Testing Medical Config:")
    medical_config = OptimizedTrainingConfig('medical')
    print(f"   Epochs: {medical_config.get('epochs')}")
    print(f"   Degrees: {medical_config.get('degrees')}")
    print(f"   Box loss weight: {medical_config.get('box')}")
    
    # 测试hyp.yaml生成
    print("\n3. Testing hyp.yaml generation:")
    yaml_content = medical_config.get_hyp_yaml_content()
    print(f"   YAML length: {len(yaml_content)} chars")
    print("   First 200 chars:")
    print(yaml_content[:200])
    
    # 测试训练参数获取
    print("\n4. Testing training args:")
    args = get_training_args(medical_config.to_dict())
    print(f"   Number of args: {len(args)}")
    print(f"   Key args: epochs={args['epochs']}, batch={args['batch']}, imgsz={args['imgsz']}")
    
    # 测试预设配置
    print("\n5. Testing preset configs:")
    high_res = get_preset_config('high_res')
    print(f"   High res: imgsz={high_res.get('imgsz')}, batch={high_res.get('batch')}")
    
    small_obj = get_preset_config('small_object')
    print(f"   Small object: box={small_obj.get('box')}, copy_paste={small_obj.get('copy_paste')}")
    
    # 测试数据增强管道
    print("\n6. Testing augmentation pipeline:")
    transform = get_medical_augmentation_pipeline()
    if transform is not None:
        print(f"   Augmentation pipeline created successfully")
        print(f"   Number of transforms: {len(transform.transforms)}")
    else:
        print("   Albumentations not installed")
    
    print("\n✓ All tests passed!")
