"""Add role-based access control fields

Revision ID: 3315d3fc5c81
Revises: 
Create Date: 2026-04-07 22:41:42.647554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3315d3fc5c81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 检查并删除旧表(如果存在)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    if 'ai_model_history' in existing_tables:
        op.drop_table('ai_model_history')
    if 'ai_model_configs' in existing_tables:
        op.drop_table('ai_model_configs')
    
    # 扩展User表 - 添加新字段(检查是否已存在)
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'full_name' not in users_columns:
            batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        if 'email' not in users_columns:
            batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        if 'phone' not in users_columns:
            batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
    
    # 数据迁移: 为现有用户设置默认角色为'admin'(保持向后兼容)
    # 只更新role为NULL或空字符串的用户
    op.execute("""
        UPDATE users 
        SET role = 'admin' 
        WHERE role IS NULL OR role = ''
    """)
    
    # 添加索引: User.role(检查是否已存在)
    users_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    if 'ix_users_role' not in users_indexes:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.create_index('ix_users_role', ['role'], unique=False)
    
    # 扩展DetectionHistory表 - 添加患者关联和诊断字段(检查是否已存在)
    detection_columns = [col['name'] for col in inspector.get_columns('detection_history')]
    with op.batch_alter_table('detection_history', schema=None) as batch_op:
        if 'patient_id' not in detection_columns:
            batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        if 'diagnosis' not in detection_columns:
            batch_op.add_column(sa.Column('diagnosis', sa.Text(), nullable=True))
        if 'follow_up_notes' not in detection_columns:
            batch_op.add_column(sa.Column('follow_up_notes', sa.Text(), nullable=True))
        
        # 添加外键约束(检查是否已存在)
        detection_fks = [fk['name'] for fk in inspector.get_foreign_keys('detection_history')]
        if 'fk_detection_history_patient_id' not in detection_fks:
            batch_op.create_foreign_key('fk_detection_history_patient_id', 'users', ['patient_id'], ['id'])
    
    # 数据迁移: 现有DetectionHistory记录的patient_id默认为NULL(已经是nullable=True)
    # 不需要额外操作,新列默认值就是NULL
    
    # 添加索引: DetectionHistory.patient_id(检查是否已存在)
    detection_indexes = [idx['name'] for idx in inspector.get_indexes('detection_history')]
    if 'ix_detection_history_patient_id' not in detection_indexes:
        with op.batch_alter_table('detection_history', schema=None) as batch_op:
            batch_op.create_index('ix_detection_history_patient_id', ['patient_id'], unique=False)
    
    # 创建AIConversation表(如果不存在)
    # 由于之前可能通过db.create_all()创建了表,需要检查表是否存在
    if 'ai_conversations' not in existing_tables:
        op.create_table('ai_conversations',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('patient_id', sa.Integer(), nullable=False),
            sa.Column('session_id', sa.String(length=50), nullable=False),
            sa.Column('message_type', sa.String(length=20), nullable=False),
            sa.Column('message_content', sa.Text(), nullable=False),
            sa.Column('context_report_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['context_report_id'], ['detection_history.id'], ),
            sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # 添加索引: AIConversation.patient_id, session_id, created_at(检查是否已存在)
    ai_conv_indexes = [idx['name'] for idx in inspector.get_indexes('ai_conversations')]
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        if 'ix_ai_conversations_patient_id' not in ai_conv_indexes:
            batch_op.create_index('ix_ai_conversations_patient_id', ['patient_id'], unique=False)
        if 'ix_ai_conversations_session_id' not in ai_conv_indexes:
            batch_op.create_index('ix_ai_conversations_session_id', ['session_id'], unique=False)
        if 'ix_ai_conversations_created_at' not in ai_conv_indexes:
            batch_op.create_index('ix_ai_conversations_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除AIConversation表的索引和表
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_conversations_created_at')
        batch_op.drop_index('ix_ai_conversations_session_id')
        batch_op.drop_index('ix_ai_conversations_patient_id')
    
    op.drop_table('ai_conversations')
    
    # 删除DetectionHistory表的索引和列
    with op.batch_alter_table('detection_history', schema=None) as batch_op:
        batch_op.drop_index('ix_detection_history_patient_id')
        batch_op.drop_constraint('fk_detection_history_patient_id', type_='foreignkey')
        batch_op.drop_column('follow_up_notes')
        batch_op.drop_column('diagnosis')
        batch_op.drop_column('patient_id')
    
    # 删除User表的索引和列
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('full_name')

    # 恢复旧表
    op.create_table('ai_model_configs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('model_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=80), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_model_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=200), nullable=False),
    sa.Column('api_key', sa.TEXT(), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('use_count', sa.INTEGER(), nullable=True),
    sa.Column('last_used', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
